### ISSUE TITLE
UMLS login failed

### ISSUE THREAD

**Issue by devasakshay** [MeasureAuthoringTool/MeasureAuthoringTool_Release#3]
UMLS login failed using vsac.nlm.nih.gov creadentials

Possible reason: ssl certificate expired for vsac.nlm.nih.gov

Please look into concern.

Thanks
![screenshot from 2016-10-17 11-47-54aa](https://cloud.githubusercontent.com/assets/12794924/19438081/c58c8192-9495-11e6-88f0-e305dd3f9829.png)
![screenshot-192 168 1 35 8888 2016-10-17 18-04-18](https://cloud.githubusercontent.com/assets/12794924/19438086/cb08bdf2-9495-11e6-9c96-ea5f6b7c20ee.png)
@MeasureAuthoringTool

**Comment by MeasureAuthoringTool** [comment]
Hi devasakshay,
Do you see any exceptions on your server logs/eclipse console?
If so, Can you please paste/attach them here?

Also, can you please paste your VM arguments & their values here,
ex: -Dvsac_proxy_host etc

Thanks,
Chinmay

**Comment by MeasureAuthoringTool** [comment]
Hi devasakshay,
Do you see any exceptions on your server logs/eclipse console?
If so, Can you please paste/attach them here?

Also, can you please paste your VM arguments & their values here,
ex: -Dvsac_proxy_host etc

Thanks,
Chinmay

**Comment by devasakshay** [comment]
Hello,

Issue was from VSAC api. it was down for that period
