### ISSUE TITLE
Code modifiers are not supported.

### ISSUE THREAD

**Issue by devasakshay** [MeasureAuthoringTool/MeasureAuthoringTool_Release#5]
The current version of measure authoring tool does not support the concept of Code Modifiers. 

Reference link :http://www.priorityhealth.com/provider/manual/billing-and-payment/services/anesthesia/modifiers 

let me know how this can be used in Measure authoring tool while implementing clause logic.

**Comment by MeasureAuthoringTool** [comment]
Hi devasakshay,
Apologies for the delay in response.
Right now the MAT is tightly coupled to the Quality Data Model (QDM). Please contact the QDM steward to find out how code modifiers should be handled in QDM. For questions or comments on the QDM, please contact qdm@esacinc.com.
